# Generated by Django 5.2.4 on 2025-07-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handzettel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supermarkt', models.CharField(max_length=30)),
                ('titel', models.CharField(max_length=100)),
                ('datei', models.FileField(upload_to='handzettel/')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
